### ISSUE TITLE
Alt commands

### ISSUE THREAD

**Issue by LovinLifee** [redpois0n/swing-terminal#1]
When using the terminal when you use commands such as Alt + C commonly used to exit a program in side of the shell, it just doesn't allow you to input any more commands and it spews null pointer exceptions in to the console.

**Comment by LovinLifee** [comment]
Also, after you input numerous commands and then clear the console, the scroll bar won't be reset so when you type in a command it's not visible so you have to scroll back to the top of the screen.

**Comment by wille** [comment]
Thank you 

Will be fixed shortly

**Comment by LovinLifee** [comment]
Another bug, when you select and then try to right click for copy, it will deselect your selected text unless you right click from the top left corner of the selection. Because of the 600MS sleep in your update thread it makes the selection rendering a little slow.

You could also make the selecting like cmd where you have to right click mark, select the text and then right click to automatically select everything you have highlighted.

**Comment by wille** [comment]
Thank you

This component is not near finished, but I have not had the time to fix it yet. It's not supposed to be used in anything yet.
